# Generated by Django 4.2.16 on 2024-09-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('other_links', models.TextField(max_length=500)),
                ('skills', models.TextField()),
                ('edu_10', models.CharField(max_length=4)),
                ('edu_10_year', models.CharField(max_length=10)),
                ('edu_10_institute', models.CharField(max_length=150)),
                ('edu_12', models.CharField(max_length=4)),
                ('edu_12_year', models.CharField(max_length=10)),
                ('edu_12_institute', models.CharField(max_length=150)),
                ('edu_grad_name', models.CharField(max_length=100)),
                ('edu_grad_spz', models.CharField(max_length=100)),
                ('edu_grad_start', models.CharField(max_length=10)),
                ('edu_grad_end', models.CharField(max_length=10)),
                ('edu_grad_institute', models.CharField(max_length=150)),
                ('project_title', models.CharField(max_length=150)),
                ('project_link', models.URLField()),
                ('project_disc', models.TextField()),
            ],
        ),
    ]
