# Generated by Django 4.2.16 on 2024-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='project_link',
            field=models.TextField(),
        ),
    ]
