# Generated by Django 4.2.16 on 2024-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume_builder', '0002_alter_resumedata_project_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeData',
            new_name='ResumeModel',
        ),
    ]
